---
- name: Restart node-exporter
  become: true
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    daemon_reload: true

- name: Restart home-assistant
  ansible.builtin.systemd:
    name: home-assistant
    state: restarted
    daemon_reload: true
    scope: user
