---
- name: Restart home-assistant
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: home-assistant
    state: restarted
    daemon_reload: true
    scope: user

- name: Restart grafana-alloy
  become: true
  become_user: "{{ podman_user }}"
  ansible.builtin.systemd:
    name: grafana-alloy
    state: restarted
    daemon_reload: true
    scope: user
