---
all:
  hosts:
    dalaran:
      node_exporter_arch: arm64

immutable:
  hosts:
    dalaran:

podman:
  hosts:
    dalaran:
      podman_containers:
        - home_assistant
        - grafana_alloy
