---
# Global defaults
podman_user: podman
podman_group: podman
podman_volume_root: /var/containers/

# Node Exporter
node_exporter_version: latest

# Home Assistant
home_assistant_version: 2024.12.1
home_assistant_zigbee_device: /dev/ttyUSB0

# Grafana Alloy
grafana_alloy_version: v1.5.1
