---
- name: Create ansible group
  ansible.builtin.group:
    name: ansible
    state: present

- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    group: ansible
    shell: /bin/bash
    create_home: true
    state: present

- name: Add ansible user to sudoers
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: "0440"

- name: Ensure ansible user has .ssh directory
  ansible.builtin.file:
    name: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: "0700"

- name: Ensure ansible user has authorized_keys file
  ansible.builtin.copy:
    dest: /home/ansible/.ssh/authorized_keys
    content: "{{ ansible_user_public_key }}"
    owner: ansible
    group: ansible
    mode: "0600"
