---
- name: Create node exporter quadlet
  become: true
  containers.podman.podman_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:{{ node_exporter_version }}
    state: quadlet
    quadlet_options:
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=multi-user.target
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9100
    command: --path.rootfs=/host
    pid: host
  notify: Restart node-exporter

- name: Enable node exporter quadlet
  become: true
  ansible.builtin.systemd:
    name: node-exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Test node exporter is reachable
  ansible.builtin.uri:
    url: http://localhost:9100/metrics
    status_code: 200
    timeout: 5
    return_content: false
  delay: 5
