---
- name: Manage Podman Containers
  hosts: podman
  
  pre_tasks:
    - name: Get dialout group from /usr/lib/group
      become: true
      ansible.builtin.command:
        cmd: grep ^dialout /usr/lib/group
      changed_when: false
      register: dialout_group

    - name: Ensure dialout group is present
      become: true
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^dialout'
        line: "{{ dialout_group.stdout }}"
        state: present

    - name: Ensure user is in dialout group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: dialout

  tasks:
    - name: Manage common containers
      ansible.builtin.include_role:
        name: podman_containers
        tasks_from: "{{ item }}.yaml"
        apply:
          tags:
            - "{{ item }}"
      tags: always
      loop:
        - node_exporter

    - name: Manage specific containers
      ansible.builtin.include_role:
        name: podman_containers
        tasks_from: "{{ item }}.yaml"
        apply:
          tags:
            - "{{ item }}"
      tags: always
      loop: "{{ podman_containers }}"
