---
- name: Manage Podman Containers
  hosts: podman
  
  pre_tasks:
    - name: Setup podman for quadlets
      ansible.builtin.import_role:
        name: podman_quadlet_host
      tags: podman

  tasks:
    - name: Manage containers
      ansible.builtin.include_role:
        name: podman_containers
        tasks_from: "{{ item }}.yaml"
        apply:
          tags:
            - "{{ item }}"
            - containers
      tags: always
      loop: "{{ podman_containers }}"
